

export const linkData = [
  {
    id: 1,
    title: "Estefanos",
    slug: "estefanos",
    images: [
      "/img/estefano.jpg",
      "/img/estefano2.jpg",      
    ],
    description:
      "Esta JR Suite tiene el Sello Gaviana. Está conformada por una habitación con una amplia y cómoda cama king size. Además, la Suite Estefanos incluye una práctica estancia. Resulta ideal para viaje en pareja.",
    guests: 2,
    amenities: ["Vista a la alberca"],
    size: "341 ft² aprox",
    included: [
      "AA",
      "Secadora de cabello",
      "Caja de seguridad",
      "Plancha",
      "Tabla de planchar",
    ],
  },
  {
    id: 2,
    title: "Patmos",
    slug: "patmos",
    images: [
      "/img/patmoss.jpg",
      "/img/patmoss2.jpg",
      "/img/patmoss3.jpg",
    ],
    description:
      "Ideal para quienes buscan practicidad y sencillez, Patmos ofrece todo lo básico para pasar una estancia agradable. Con dos camas queen size, tiene capacidad para 4 huéspedes.",
    guests: 4,
    amenities: ["Vista a la alberca"],
    size: "280 ft² aprox",
    included: [
      "AA",
      "Secadora de cabello",
      "Caja de seguridad",
      "SMART TV",
      "Plancha",
      "Tabla de planchar",
    ],
  },
  {
    id: 3,
    title: "Cristiana",
    slug: "cristiana",
    images: [
      "/img/cristiana.jpg",
      "/img/cristiana2.jpg",      
    ],
    description:
      "Cristiana está pensada en quienes buscan una habitación donde puedan estar cómodos con el equipamiento básico y un ambiente agradable. Cuenta con una cama king size y Smart TV.",
    guests: 2,
    amenities: ["Vista a la alberca"],
    size: "245 ft² aprox",
    included: [
      "AA",
      "Secadora de cabello",
      "Caja de seguridad",
      "SMART TV",
      "Plancha",
      "Tabla de planchar",
    ],
  },
  {
    id: 4,
    title: "Rodas",
    slug: "rodas",
    images: [
      "/img/rodas.jpg",
      "/img/rodas2.jpg",
      "/img/rodas3.jpg",
    ],
    description:
      "Amplia suite con 2 camas queen en una de las habitaciones, 1 cama queen en la otra recámara, cuenta con baño y medio y garantiza vista al mar. Además de contar con un amplio balcón.",
    guests: 6,
    amenities: ["Vista parcial al mar"],
    size: "352 ft² aprox",
    included: [
      "Horno de microondas",
      "Refrigerador",
      "Cafetera eléctrica",
      "SMART TV",
      "Secadora de cabello",
      "Caja de seguridad",
      "Plancha",
      "Tabla de planchar",
    ],
  },
  {
    id: 5,
    title: "Milos",
    slug: "milos",
    images: [
      "/img/milos.jpg",
      "/img/milos2.jpg",      
    ],
    description:
      "Amplia Suite ideal para disfrutarla en familia o con amigos que desean aprovechar al máximo el tiempo juntos. Cuenta con dos camas queen size, sala con sofá-cama, cocina semi-equipada y vista al mar garantizada. Además de contar con un amplio balcón.",
    guests: 4,
    amenities: ["Vista al mar"],
    size: "352 ft² aprox",
    included: [
      "Sartén eléctrico",
      "Horno de microondas",
      "Refrigerador",
      "Cafetera eléctrica",
      "AA",
      "Secadora de cabello",
      "Caja de seguridad",
      "Plancha",
      "Tabla de planchar",
    ],
  },
  {
    id: 6,
    title: "Creta",
    slug: "creta",
    images: [
      "/img/creta.jpg",
      "/img/creta2.jpg",      
    ],
    description:
      "La Suite Creta es la mejor opción para viaje en parejas. Cuenta con dos habitaciones, cada una con cama king size. La suite tiene dos baños completos, sala, comedor, cocina semi-equipada con refrigerador y Smart TV. Además de contar con un amplio balcón.",
    guests: 5,
    amenities: ["Vista a la ciudad"],
    size: "330 ft² aprox",
    included: [
      "Sartén eléctrico",
      "Horno de microondas",
      "Refrigerador",
      "Cafetera eléctrica",
      "SMART TV",
      "Secadora de cabello",
      "Caja de seguridad",
      "Plancha",
      "Tabla de planchar",      
    ],
  },
  {
    id: 7,
    title: "Mykonos",
    slug: "mykonos",
    images: [
      "/img/mykonos.jpg",
      "/img/mykonos2.jpg",
      "/img/mykonos3.jpg",
    ],
    description:
      "Diseñada para quienes gustan de confort y privacidad, excelente opción para parejas, cuenta con una pequeña estancia, recámara privada con una cama King.",
    guests: 2,
    amenities: ["Vista a la alberca"],
    size: "326 ft² aprox",
    included: [
      "Horno de microondas",
      "Refrigerador",
      "Cafetera eléctrica",
      "SMART TV",
      "Caja de seguridad",
      "Secadora de cabello",
      "Plancha",
      "Tabla de planchar",
    ],
  },
]
